# Generated by Django 4.1.6 on 2023-02-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-deadline", "priority"]},
        ),
    ]
